# Generated by Django 4.2.13 on 2024-05-31 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('messanger', 'Messanger'), ('invite', 'Invite'), ('friend-request', 'FriendRequest'), ('info', 'Info')], default='info', max_length=30),
        ),
    ]
