# Generated by Django 4.2.14 on 2024-07-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_notification_action_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('messenger', 'Messenger'), ('invite', 'Invite'), ('friend-request', 'FriendRequest'), ('info', 'Info')], default='info', max_length=30),
        ),
    ]
