# Generated by Django 4.2.13 on 2024-06-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatmessage_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='type',
            field=models.CharField(choices=[('private', 'text'), ('group', 'image')], default='text', max_length=10),
        ),
    ]
