# Generated by Django 4.2.13 on 2024-07-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_removedroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('notification', 'Notification')], default='text', max_length=12),
        ),
    ]
