# Generated by Django 4.2.13 on 2024-07-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_chatmessage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='type',
            field=models.CharField(choices=[('private', 'text'), ('group', 'image')], default='text', max_length=10),
        ),
    ]
