# Generated by Django 4.2.13 on 2024-07-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_chatmessage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('text', 'Image')], default='text', max_length=10),
        ),
    ]
