# Generated by Django 4.2.13 on 2024-05-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_xp',
            field=models.IntegerField(default=0),
        ),
    ]
