# Generated by Django 5.0.4 on 2024-05-02 04:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TurnementsRegistredPlayers',
            new_name='TournamentsRegisteredPlayers',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='registred_users',
        ),
        migrations.AddField(
            model_name='tournament',
            name='registered_users',
            field=models.ManyToManyField(through='game.TournamentsRegisteredPlayers', to=settings.AUTH_USER_MODEL),
        ),
    ]
