# Generated by Django 4.2.16 on 2024-09-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='game_type',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online'),
        ),
    ]
