# Generated by Django 5.0.4 on 2024-05-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_brackets_player_alter_brackets_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brackets',
            name='round_number',
            field=models.IntegerField(default=1),
        ),
    ]
