# Generated by Django 5.0.4 on 2024-05-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_stream_tournament_streams'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_monetized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
