# Generated by Django 4.2.13 on 2024-05-17 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_tournament_is_monetized_tournament_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='icon',
            field=models.URLField(blank=True, null=True),
        ),
    ]
