# Generated by Django 4.2.13 on 2024-05-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_matchup_winner_matchup_game_over_delete_matchstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='first_player_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchup',
            name='second_player_score',
            field=models.IntegerField(default=0),
        ),
    ]
