# Generated by Django 4.2.13 on 2024-05-30 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0009_matchup_first_player_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='owener',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owener', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
