# Generated by Django 4.2.13 on 2024-06-03 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0012_remove_matchup_game_matchup_game_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchup',
            name='first_player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='first_player', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matchup',
            name='second_player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='second_player', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
