# Generated by Django 4.2.13 on 2024-06-07 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_alter_matchup_first_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='round_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tournament',
            name='uuid',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
