# Generated by Django 4.2.13 on 2024-06-07 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0014_matchup_round_number_tournament_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchup',
            name='second_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_player', to=settings.AUTH_USER_MODEL),
        ),
    ]
