# Generated by Django 4.2.13 on 2024-06-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_alter_matchup_second_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchup',
            name='game_uuid',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
