# Generated by Django 4.2.13 on 2024-06-12 21:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_alter_tournament_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchup',
            name='game_uuid',
            field=models.CharField(default=uuid.uuid4, max_length=200, unique=True),
        ),
    ]
