# Generated by Django 4.2.15 on 2024-09-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_alter_matchup_game_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentsregisteredplayers',
            name='alias',
            field=models.CharField(default=None),
        ),
    ]
