# Generated by Django 4.2.15 on 2024-09-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_tournamentsregisteredplayers_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentsregisteredplayers',
            name='alias',
            field=models.CharField(null=True),
        ),
    ]
