# Generated by Django 4.2.16 on 2024-09-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_alter_tournamentsregisteredplayers_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='ongoing',
            field=models.BooleanField(default=False),
        ),
    ]
