# Generated by Django 4.2.15 on 2024-09-13 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_tournament_ongoing'),
    ]

    operations = [
        migrations.AddField(
            model_name='brackets',
            name='alias',
            field=models.CharField(null=True),
        ),
    ]
